"""
Django settings for avvento_hrmis project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import dj_database_url
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'My$ecretKeyForDevelopmentOnly!ChangeMeInProduction')

# SECURITY WARNING: don't run with debug turned on in production!
# Default DEBUG=True for local SQLite dev; production sets DEBUG=False via env (Render).
DEBUG = os.environ.get(
    'DEBUG',
    'False' if os.environ.get('DATABASE_URL') else 'True',
) == 'True'

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'True') == 'True'
    SESSION_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SECURE = True
    CSRF_COOKIE_SAMESITE = 'Lax'
    SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = 'same-origin'
    X_FRAME_OPTIONS = 'DENY'
    # Refuse the well-known development secret in production.
    if SECRET_KEY == 'My$ecretKeyForDevelopmentOnly!ChangeMeInProduction':
        from django.core.exceptions import ImproperlyConfigured
        raise ImproperlyConfigured('Set a unique SECRET_KEY in production.')

# Session hardening
SESSION_COOKIE_AGE = int(os.environ.get('SESSION_COOKIE_AGE', str(60 * 60 * 8)))  # 8 hours
SESSION_SAVE_EVERY_REQUEST = True
SESSION_IDLE_TIMEOUT_SECONDS = int(os.environ.get('SESSION_IDLE_TIMEOUT_SECONDS', str(60 * 30)))  # 30 min idle
LOGIN_LOCKOUT_THRESHOLD = int(os.environ.get('LOGIN_LOCKOUT_THRESHOLD', '5'))
LOGIN_LOCKOUT_WINDOW_SECONDS = int(os.environ.get('LOGIN_LOCKOUT_WINDOW_SECONDS', '900'))
MAX_UPLOAD_BYTES = int(os.environ.get('MAX_UPLOAD_BYTES', str(10 * 1024 * 1024)))
ENCRYPT_BACKUPS = os.environ.get('ENCRYPT_BACKUPS', 'True' if not DEBUG else 'False') == 'True'
CONTENT_SECURITY_POLICY = os.environ.get(
    'CONTENT_SECURITY_POLICY',
    "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; "
    "img-src 'self' data: blob:; font-src 'self' data:; connect-src 'self'; "
    "frame-ancestors 'none'; base-uri 'self'; form-action 'self'",
)

ALLOWED_HOSTS = ['localhost', '127.0.0.1']

_extra_hosts = os.environ.get('ALLOWED_HOSTS', '')
if _extra_hosts:
    ALLOWED_HOSTS.extend(host.strip() for host in _extra_hosts.split(',') if host.strip())

_render_hostname = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if _render_hostname:
    ALLOWED_HOSTS.append(_render_hostname)

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
]
if _render_hostname:
    CSRF_TRUSTED_ORIGINS.append(f'https://{_render_hostname}')

_extra_csrf = os.environ.get('CSRF_TRUSTED_ORIGINS', '')
if _extra_csrf:
    CSRF_TRUSTED_ORIGINS.extend(origin.strip() for origin in _extra_csrf.split(',') if origin.strip())

CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
]
CORS_ALLOW_CREDENTIALS = True
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party
    'rest_framework',
    'corsheaders',
    'drf_spectacular',
    # Local apps
    'api',
    'accounts',
    'departments',
    'employees',
    'kin',
    'attendance',
    'leaves',
    'recruitment',
    'payroll',
    'performance',
    'training',
    'reports',
    'assets',
    'exits',
    'shifts',
    'expenses',
    'surveys',
    'leave_policies',
    'benefits',
    'discipline',
    'workflows',
    'documents',
    'integrations',
    'compliance',
    'django_q',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'api.middleware.RequestIDMiddleware',
    'api.middleware.DeprecationMiddleware',
    'api.middleware.SecurityHeadersMiddleware',
    'api.middleware.SessionIdleTimeoutMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'avvento_hrmis.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'api' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'avvento_hrmis.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if os.environ.get('DATABASE_URL'):
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ['DATABASE_URL'],
            conn_max_age=600,
            ssl_require=not DEBUG,
        )
    }
elif os.environ.get('POSTGRES_NAME'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ['POSTGRES_NAME'],
            'USER': os.environ.get('POSTGRES_USER', 'postgres'),
            'PASSWORD': os.environ.get('POSTGRES_PASSWORD', ''),
            'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
            'PORT': os.environ.get('POSTGRES_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Africa/Kampala'
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = '/static/'

REACT_BUILD_DIR = BASE_DIR / 'frontend' / 'dist'

STATICFILES_DIRS = []
_react_assets = REACT_BUILD_DIR / 'assets'
if _react_assets.exists():
    STATICFILES_DIRS.append(_react_assets)

STATIC_ROOT = BASE_DIR / 'staticfiles'

if REACT_BUILD_DIR.exists():
    WHITENOISE_ROOT = REACT_BUILD_DIR

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Media files — local by default; S3 when AWS_STORAGE_BUCKET_NAME is set
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

if os.environ.get('AWS_STORAGE_BUCKET_NAME'):
    STORAGES = {
        'default': {
            'BACKEND': 'storages.backends.s3boto3.S3Boto3Storage',
        },
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
        },
    }
    AWS_STORAGE_BUCKET_NAME = os.environ['AWS_STORAGE_BUCKET_NAME']
    AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME', 'us-east-1')
    AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID', '')
    AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY', '')
    AWS_S3_CUSTOM_DOMAIN = os.environ.get('AWS_S3_CUSTOM_DOMAIN', '')
    AWS_DEFAULT_ACL = None
    AWS_QUERYSTRING_AUTH = True
    AWS_S3_FILE_OVERWRITE = False
    if AWS_S3_CUSTOM_DOMAIN:
        MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/'

# Auth
AUTH_USER_MODEL = 'accounts.CustomUser'
LOGIN_URL = '/login'
ALLOW_PUBLIC_REGISTRATION = os.environ.get('ALLOW_PUBLIC_REGISTRATION', 'False') == 'True'
# Require admin MFA in production; off by default for local SQLite dev (set True to test MFA flow).
ENFORCE_MFA_FOR_ADMINS = os.environ.get(
    'ENFORCE_MFA_FOR_ADMINS',
    'True' if os.environ.get('DATABASE_URL') else 'False',
) == 'True'
# Managers: default on in production (DATABASE_URL present)
ENFORCE_MFA_FOR_MANAGERS = os.environ.get(
    'ENFORCE_MFA_FOR_MANAGERS',
    'True' if os.environ.get('DATABASE_URL') else 'False',
) == 'True'

# Email
EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend',
)
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@hrmis.local')
HR_NOTIFY_EMAIL = os.environ.get('HR_NOTIFY_EMAIL', '')

# SSO (Google / Microsoft)
GOOGLE_OAUTH_CLIENT_ID = os.environ.get('GOOGLE_OAUTH_CLIENT_ID', '')
GOOGLE_OAUTH_CLIENT_SECRET = os.environ.get('GOOGLE_OAUTH_CLIENT_SECRET', '')
MICROSOFT_OAUTH_CLIENT_ID = os.environ.get('MICROSOFT_OAUTH_CLIENT_ID', '')
MICROSOFT_OAUTH_CLIENT_SECRET = os.environ.get('MICROSOFT_OAUTH_CLIENT_SECRET', '')
MICROSOFT_OAUTH_TENANT = os.environ.get('MICROSOFT_OAUTH_TENANT', 'common')
SSO_CALLBACK_BASE_URL = os.environ.get('SSO_CALLBACK_BASE_URL', 'http://localhost:8000')
SSO_FRONTEND_REDIRECT = os.environ.get('SSO_FRONTEND_REDIRECT', 'http://localhost:5173/dashboard')
SSO_AUTO_PROVISION = os.environ.get('SSO_AUTO_PROVISION', 'False') == 'True'
WEBHOOKS_ENABLED = os.environ.get('WEBHOOKS_ENABLED', 'True') == 'True'

ENFORCE_MFA_FOR_PAYROLL = os.environ.get(
    'ENFORCE_MFA_FOR_PAYROLL',
    'True' if os.environ.get('DATABASE_URL') else 'False',
) == 'True'

FIELD_ENCRYPTION_KEY = os.environ.get('FIELD_ENCRYPTION_KEY', '')
FIELD_ENCRYPTION_KEY_PREVIOUS = os.environ.get('FIELD_ENCRYPTION_KEY_PREVIOUS', '')
REQUIRE_FIELD_ENCRYPTION_KEY = os.environ.get(
    'REQUIRE_FIELD_ENCRYPTION_KEY',
    'True' if not DEBUG else 'False',
) == 'True'
if REQUIRE_FIELD_ENCRYPTION_KEY and not FIELD_ENCRYPTION_KEY:
    from django.core.exceptions import ImproperlyConfigured
    raise ImproperlyConfigured(
        'FIELD_ENCRYPTION_KEY must be set in production. '
        'Generate with: python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"',
    )

BACKUP_S3_BUCKET = os.environ.get('BACKUP_S3_BUCKET', '')
BACKUP_S3_PREFIX = os.environ.get('BACKUP_S3_PREFIX', 'hrmis-backups/')
BACKUP_S3_SSE = os.environ.get('BACKUP_S3_SSE', 'AES256')  # AES256 or aws:kms
BACKUP_S3_SSE_KMS_KEY_ID = os.environ.get('BACKUP_S3_SSE_KMS_KEY_ID', '')

Q_CLUSTER = {
    'name': 'hrmis',
    'workers': int(os.environ.get('Q_WORKERS', '2')),
    'timeout': 300,
    'retry': 360,
    'queue_limit': 50,
    'bulk': 10,
    'orm': 'default',
    'catch_up': True,
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'api.authentication.APIKeyAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
        'api.permissions.RequiresMFASetupComplete',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 25,
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': os.environ.get('API_THROTTLE_ANON', '60/minute'),
        'user': os.environ.get('API_THROTTLE_USER', '600/minute'),
        'login': os.environ.get('API_THROTTLE_LOGIN', '10/minute'),
        'mfa': os.environ.get('API_THROTTLE_MFA', '10/minute'),
        'export': os.environ.get('API_THROTTLE_EXPORT', '30/minute'),
        'scim': os.environ.get('API_THROTTLE_SCIM', '60/minute'),
    },
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Avvento HRMIS API',
    'DESCRIPTION': 'Human Resource Management Information System API',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

SENTRY_DSN = os.environ.get('SENTRY_DSN', '')
if SENTRY_DSN:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[DjangoIntegration()],
        traces_sample_rate=float(os.environ.get('SENTRY_TRACES_SAMPLE_RATE', '0.1')),
        environment=os.environ.get('RENDER_SERVICE_NAME', 'development'),
        send_default_pii=False,
    )