# Generated by Django 6.0.5 on 2026-06-25 06:45

from django.db import migrations, models


def seed_default_policies(apps, schema_editor):
    Policy = apps.get_model('compliance', 'DataRetentionPolicy')
    defaults = [
        ('audit_logs', 730, 'Immutable audit trail for compliance reviews (default 2 years).'),
        ('webhook_deliveries', 90, 'Outbound webhook delivery attempts and payloads.'),
        ('notifications', 180, 'Read and unread in-app notification history.'),
    ]
    for category, days, description in defaults:
        Policy.objects.get_or_create(
            category=category,
            defaults={
                'retention_days': days,
                'description': description,
                'is_active': True,
            },
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataRetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('audit_logs', 'Audit logs'), ('webhook_deliveries', 'Webhook delivery history'), ('notifications', 'In-app notifications')], max_length=40, unique=True)),
                ('retention_days', models.PositiveIntegerField(help_text='Records older than this many days may be purged.')),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_purged_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Data retention policies',
                'ordering': ('category',),
            },
        ),
        migrations.RunPython(seed_default_policies, migrations.RunPython.noop),
    ]
