# Generated by Django 6.0.5 on 2026-06-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataretentionpolicy',
            name='category',
            field=models.CharField(choices=[('audit_logs', 'Audit logs'), ('webhook_deliveries', 'Webhook delivery history'), ('notifications', 'In-app notifications'), ('rejected_applications', 'Rejected job applications')], max_length=40, unique=True),
        ),
    ]
