# Generated by Django 6.0.5 on 2026-07-15 18:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_alter_dataretentionpolicy_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceEvidencePack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control', models.CharField(choices=[('access_control', 'Access control'), ('encryption', 'Encryption at rest'), ('backup_restore', 'Backup & restore'), ('audit_logging', 'Audit logging'), ('data_retention', 'Data retention'), ('incident_response', 'Incident response'), ('vulnerability_mgmt', 'Vulnerability management')], max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('evidence_url', models.URLField(blank=True)),
                ('owner', models.CharField(blank=True, max_length=100)),
                ('last_reviewed_at', models.DateField(blank=True, null=True)),
                ('next_review_at', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('gap', 'Gap')], default='draft', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['control', 'title'],
            },
        ),
        migrations.CreateModel(
            name='VulnerabilityFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('resolved', 'Resolved'), ('accepted', 'Risk accepted')], default='open', max_length=20)),
                ('discovered_at', models.DateField(default=django.utils.timezone.now)),
                ('due_at', models.DateField(blank=True, null=True)),
                ('resolved_at', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('remediation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-discovered_at', 'severity'],
            },
        ),
    ]
