# Generated by Django 6.0.5 on 2026-07-15 16:16

import django.db.models.deletion
from uuid import uuid4
from django.conf import settings
from django.db import migrations, models


def backfill_employee_numbers(apps, schema_editor):
    Employee = apps.get_model('employees', 'Employee')
    for employee in Employee.objects.filter(employee_number__isnull=True).iterator():
        employee.employee_number = f'EMP-{uuid4().hex[:10].upper()}'
        employee.save(update_fields=['employee_number'])


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_alter_department_options_department_parent'),
        ('employees', '0002_employee_termination'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('rank', models.PositiveIntegerField(default=1)),
                ('minimum_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('maximum_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['rank', 'code'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='cost_center',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='employment_type',
            field=models.CharField(choices=[('permanent', 'Permanent'), ('fixed_term', 'Fixed Term'), ('temporary', 'Temporary'), ('intern', 'Intern'), ('consultant', 'Consultant')], default='permanent', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='national_id_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='employee',
            name='nssf_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='employee',
            name='probation_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='tax_identification_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='account_number',
            field=models.CharField(max_length=34),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bank',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emergency_contact',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobile',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='EmploymentContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('permanent', 'Permanent'), ('fixed_term', 'Fixed Term'), ('temporary', 'Temporary'), ('internship', 'Internship'), ('consultancy', 'Consultancy')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('probation_end_date', models.DateField(blank=True, null=True)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('expired', 'Expired'), ('terminated', 'Terminated')], default='draft', max_length=15)),
                ('document', models.FileField(blank=True, null=True, upload_to='employees/contracts/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='employees.employee')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employees.jobgrade'),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='departments.department')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='employees.jobgrade')),
                ('reports_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='employees.position')),
            ],
            options={
                'ordering': ['department__name', 'title'],
            },
        ),
        migrations.CreateModel(
            name='EmploymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('hire', 'Hire'), ('promotion', 'Promotion'), ('transfer', 'Transfer'), ('grade_change', 'Grade Change'), ('salary_change', 'Salary Change'), ('contract_change', 'Contract Change'), ('exit', 'Exit')], max_length=20)),
                ('effective_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_history', to='employees.employee')),
                ('new_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='departments.department')),
                ('previous_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='departments.department')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employment_changes', to=settings.AUTH_USER_MODEL)),
                ('new_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employees.jobgrade')),
                ('previous_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employees.jobgrade')),
                ('new_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employees.position')),
                ('previous_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employees.position')),
            ],
            options={
                'ordering': ['-effective_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employees.position'),
        ),
        migrations.RunPython(backfill_employee_numbers, migrations.RunPython.noop),
    ]
