# Generated by Django 6.0.5 on 2026-07-15 17:07

import accounts.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_require_employee_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='account_number',
            field=accounts.fields.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='national_id_number',
            field=accounts.fields.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nssf_number',
            field=accounts.fields.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tax_identification_number',
            field=accounts.fields.EncryptedCharField(blank=True),
        ),
    ]
