# Generated by Django 6.0.5 on 2026-07-15 18:31

import accounts.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_maturity_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='bank',
            field=accounts.fields.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=accounts.fields.EncryptedDecimalField(blank=True, null=True),
        ),
    ]
