# Generated by Django 6.0.5 on 2026-07-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_jobgrade_organization_position_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='device_badge_id',
            field=models.CharField(blank=True, db_index=True, help_text='Biometric / RFID / device badge identifier for attendance terminals.', max_length=64),
        ),
    ]
