# Generated by Django 6.0.5 on 2026-07-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_employee_device_badge_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['last_name', 'first_name', 'id']},
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_number',
            field=models.CharField(blank=True, help_text='Staff / employee ID used across HR, payroll, and attendance.', max_length=30, unique=True),
        ),
    ]
