# Generated by Django 6.0.5 on 2026-07-19 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_maturity_features'),
        ('recruitment', '0005_use_uganda_shillings'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_postings', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='offertemplate',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_templates', to='accounts.organization'),
        ),
    ]
