# Generated by Django 6.0.5 on 2026-05-25 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('employees', '0002_employee_termination'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeavePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('leave_type', models.CharField(choices=[('annual', 'Annual Leave'), ('sick', 'Sick Leave'), ('casual', 'Casual Leave'), ('maternity', 'Maternity Leave'), ('paternity', 'Paternity Leave'), ('bereavement', 'Bereavement Leave')], max_length=20)),
                ('days_per_year', models.IntegerField()),
                ('carryforward_allowed', models.BooleanField(default=False)),
                ('carryforward_limit', models.IntegerField(blank=True, help_text='Maximum days to carry forward', null=True)),
                ('description', models.TextField(blank=True)),
                ('applicable_to_all', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('departments', models.ManyToManyField(blank=True, related_name='leave_policies', to='departments.department')),
            ],
            options={
                'verbose_name_plural': 'Leave Policies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeavePolicyAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_year', models.IntegerField()),
                ('allocated_days', models.IntegerField()),
                ('used_days', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('pending_days', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('carryforward_days', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_allocations', to='employees.employee')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='leave_policies.leavepolicy')),
            ],
            options={
                'ordering': ['-allocation_year', 'employee'],
                'unique_together': {('employee', 'policy', 'allocation_year')},
            },
        ),
    ]
