# Generated by Django 6.0.5 on 2026-05-22 19:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_employee_termination'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giver_type', models.CharField(choices=[('manager', 'Manager'), ('peer', 'Peer'), ('direct_report', 'Direct Report'), ('other', 'Other')], help_text='Relationship of feedback giver to recipient', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('withdrawn', 'Withdrawn')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('feedback_giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_given', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_received', to='employees.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication', models.IntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], help_text='Effective communication')),
                ('leadership', models.IntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], help_text='Leadership skills')),
                ('teamwork', models.IntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], help_text='Teamwork and collaboration')),
                ('reliability', models.IntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], help_text='Reliability and accountability')),
                ('initiative', models.IntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], help_text='Initiative and proactivity')),
                ('problem_solving', models.IntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], help_text='Problem-solving ability')),
                ('strengths', models.TextField(blank=True, help_text="What are this person's key strengths?")),
                ('areas_for_improvement', models.TextField(blank=True, help_text='Areas for development')),
                ('additional_comments', models.TextField(blank=True)),
                ('is_anonymous', models.BooleanField(default=False, help_text='Submit feedback anonymously')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='performance.feedbackrequest')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('closed', 'Closed'), ('archived', 'Archived')], default='planned', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_rounds_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='feedbackrequest',
            name='feedback_round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_requests', to='performance.feedbackround'),
        ),
        migrations.CreateModel(
            name='PerformanceGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_title', models.CharField(max_length=200)),
                ('goal_description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('target_metric', models.CharField(help_text='How will success be measured?', max_length=200)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='not_started', max_length=15)),
                ('progress', models.IntegerField(default=0, help_text='Progress percentage (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_goals', to='employees.employee')),
                ('set_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='feedbackrequest',
            unique_together={('feedback_round', 'recipient', 'feedback_giver')},
        ),
        migrations.CreateModel(
            name='FeedbackSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_communication', models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('avg_leadership', models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('avg_teamwork', models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('avg_reliability', models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('avg_initiative', models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('avg_problem_solving', models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('key_strengths', models.TextField(help_text='Summary of common strengths from feedback')),
                ('development_areas', models.TextField(help_text='Summary of common development areas')),
                ('recommendations', models.TextField(blank=True, help_text='Recommendations based on feedback')),
                ('total_responses', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_summary', to='employees.employee')),
                ('feedback_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='performance.feedbackround')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('employee', 'feedback_round')},
            },
        ),
        migrations.CreateModel(
            name='PerformanceAppraisal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appraisal_period_start', models.DateField()),
                ('appraisal_period_end', models.DateField()),
                ('job_knowledge', models.IntegerField(choices=[(1, 'Needs Improvement'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], help_text='Knowledge of job responsibilities')),
                ('work_quality', models.IntegerField(choices=[(1, 'Needs Improvement'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], help_text='Quality of work output')),
                ('productivity', models.IntegerField(choices=[(1, 'Needs Improvement'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], help_text='Productivity and efficiency')),
                ('communication', models.IntegerField(choices=[(1, 'Needs Improvement'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], help_text='Communication skills')),
                ('teamwork', models.IntegerField(choices=[(1, 'Needs Improvement'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], help_text='Collaboration and teamwork')),
                ('initiative', models.IntegerField(choices=[(1, 'Needs Improvement'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], help_text='Initiative and innovation')),
                ('reliability', models.IntegerField(choices=[(1, 'Needs Improvement'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], help_text='Attendance and punctuality')),
                ('overall_rating', models.IntegerField(choices=[(1, 'Needs Improvement'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], editable=False, help_text='Auto-calculated average rating')),
                ('strengths', models.TextField(help_text='Employee strengths')),
                ('areas_for_improvement', models.TextField(help_text='Areas to improve')),
                ('reviewer_comments', models.TextField(blank=True, help_text='Additional reviewer comments')),
                ('next_goals', models.TextField(help_text='Recommended goals for next period')),
                ('training_needs', models.TextField(blank=True, help_text='Training and development needs')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('completed', 'Completed')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('appraiser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appraisals_given', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisals', to='employees.employee')),
            ],
            options={
                'ordering': ['-appraisal_period_end'],
                'unique_together': {('employee', 'appraisal_period_start', 'appraisal_period_end')},
            },
        ),
    ]
