# Generated by Django 6.0.5 on 2026-05-25 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auditlog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='accounts_au_timesta_40aa9a_idx',
            old_name='accounts_au_timesta_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='accounts_au_user_id_1110c4_idx',
            old_name='accounts_au_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='accounts_au_action_918219_idx',
            old_name='accounts_au_action_idx',
        ),
    ]
