# Generated by Django 6.0.5 on 2026-06-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_accounts_au_timesta_idx_accounts_au_timesta_40aa9a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mfa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mfa_secret',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
