# Generated by Django 6.0.5 on 2026-07-15 17:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_role_permissions'),
        ('departments', '0002_alter_department_options_department_parent'),
        ('employees', '0005_enterprise_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='managed_department',
            field=models.ForeignKey(blank=True, help_text='Department scope for managers without a linked employee profile.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_by_users', to='departments.department'),
        ),
        migrations.CreateModel(
            name='SensitiveDataAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields_accessed', models.JSONField(default=list)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('accessed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensitive_access_logs', to='employees.employee')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensitive_access_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-accessed_at',),
            },
        ),
    ]
