# Generated by Django 6.0.5 on 2026-07-19 06:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_maturity_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpsAlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64)),
                ('level', models.CharField(default='warning', max_length=16)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('outcome', models.CharField(default='emitted', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('emitted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ops_alert_events', to='accounts.organization')),
            ],
            options={
                'ordering': ('-emitted_at',),
                'indexes': [models.Index(fields=['key', '-emitted_at'], name='accounts_op_key_492737_idx')],
            },
        ),
    ]
