# Generated by Django 6.0.5 on 2026-05-25 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_employee_termination'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline_type', models.CharField(choices=[('verbal_warning', 'Verbal Warning'), ('written_warning', 'Written Warning'), ('suspension', 'Suspension'), ('final_warning', 'Final Warning'), ('termination', 'Termination')], max_length=50)),
                ('reason', models.CharField(max_length=200)),
                ('detailed_reason', models.TextField()),
                ('incident_date', models.DateField()),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('under_review', 'Under Review'), ('issued', 'Issued'), ('appealed', 'Appealed'), ('closed', 'Closed')], default='initiated', max_length=20)),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('documents', models.FileField(blank=True, null=True, upload_to='discipline_documents/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_records', to='employees.employee')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_disciplines', to='employees.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisciplineAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appeal_date', models.DateField()),
                ('appeal_reason', models.TextField()),
                ('supporting_documents', models.FileField(blank=True, null=True, upload_to='appeal_documents/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('discipline', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appeal', to='discipline.discipline')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_appeals', to='employees.employee')),
            ],
        ),
    ]
