# Generated by Django 6.0.5 on 2026-07-19 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_maturity_features'),
        ('reports', '0002_enterprise_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsnapshot',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_snapshots', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='savedreport',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_reports', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='scheduledreport',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_reports', to='accounts.organization'),
        ),
    ]
