# Generated by Django 6.0.6 on 2026-07-15 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('employees', '0004_require_employee_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrdocument',
            name='expires_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hrdocument',
            name='legal_hold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hrdocument',
            name='requires_acknowledgement',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DocumentAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgements', to='documents.hrdocument')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_acknowledgements', to='employees.employee')),
            ],
            options={
                'ordering': ['-acknowledged_at'],
                'unique_together': {('document', 'employee')},
            },
        ),
    ]
