# Generated by Django 6.0.5 on 2026-07-15 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_enterprise_features'),
        ('documents', '0002_hrdocument_expires_at_hrdocument_legal_hold_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAccessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('contract', 'Employment Contract'), ('policy', 'HR Policy'), ('offer_letter', 'Offer Letter'), ('certificate', 'Certificate'), ('other', 'Other')], max_length=20)),
                ('can_view', models.BooleanField(default=True)),
                ('can_upload', models.BooleanField(default=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_access_rules', to='accounts.role')),
            ],
            options={
                'ordering': ['role__name', 'category'],
                'unique_together': {('role', 'category')},
            },
        ),
    ]
