# Generated by Django 6.0.6 on 2026-07-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_leavebalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='is_half_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leave',
            name='working_days',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='total_days',
            field=models.FloatField(default=0, help_text='Total leave days allocated'),
        ),
    ]
