# Generated by Django 6.0.5 on 2026-05-25 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('employees', '0002_employee_termination'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('benefit_type', models.CharField(choices=[('health', 'Health Insurance'), ('retirement', 'Retirement Plan'), ('education', 'Education Assistance'), ('wellness', 'Wellness Program'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('provider', models.CharField(blank=True, max_length=100)),
                ('cost_per_employee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('employer_contribution', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('employee_contribution', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('applicable_to_all', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('departments', models.ManyToManyField(blank=True, related_name='benefits', to='departments.department')),
            ],
            options={
                'verbose_name_plural': 'Benefits',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField()),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive'), ('terminated', 'Terminated')], default='pending', max_length=20)),
                ('plan_type', models.CharField(blank=True, help_text='e.g., Premium, Basic, Family', max_length=100)),
                ('monthly_deduction', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('beneficiary_name', models.CharField(blank=True, max_length=200)),
                ('beneficiary_relationship', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('benefit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='benefits.benefit')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_benefits', to='employees.employee')),
            ],
            options={
                'ordering': ['-enrollment_date'],
                'unique_together': {('employee', 'benefit')},
            },
        ),
    ]
