# Generated by Django 6.0.5 on 2026-05-25 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_salary_timestamps'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salary',
            options={'ordering': ['-year', '-month']},
        ),
        migrations.AlterField(
            model_name='salary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 5, 25, 15, 22, 59, 126499, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
