# Generated by Django 6.0.5 on 2026-07-15 16:05

from django.db import migrations, models


def recalculate_existing_payroll(apps, schema_editor):
    from payroll.uganda import calculate_statutory_payroll

    Salary = apps.get_model('payroll', 'Salary')
    for salary in Salary.objects.all().iterator():
        gross = salary.basic_salary + salary.allowances + salary.taxable_benefits
        statutory = calculate_statutory_payroll(gross, salary.month)
        salary.gross_salary = gross
        salary.chargeable_income = statutory['chargeable_income']
        salary.tax = statutory['paye']
        salary.nssf_employee = statutory['nssf_employee']
        salary.nssf_employer = statutory['nssf_employer']
        salary.local_service_tax = statutory['local_service_tax']
        salary.net_salary = (
            gross
            - salary.deductions
            - salary.tax
            - salary.nssf_employee
            - salary.local_service_tax
        )
        salary.status = 'paid' if salary.is_paid else 'draft'
        salary.save(update_fields=[
            'gross_salary', 'chargeable_income', 'tax', 'nssf_employee',
            'nssf_employer', 'local_service_tax', 'net_salary', 'status',
        ])


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_alter_salary_options_alter_salary_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='chargeable_income',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=16),
        ),
        migrations.AddField(
            model_name='salary',
            name='gross_salary',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=16),
        ),
        migrations.AddField(
            model_name='salary',
            name='is_resident',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='salary',
            name='is_secondary_employment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salary',
            name='local_service_tax',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=16),
        ),
        migrations.AddField(
            model_name='salary',
            name='lst_applicable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='salary',
            name='nssf_applicable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='salary',
            name='nssf_employee',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=16),
        ),
        migrations.AddField(
            model_name='salary',
            name='nssf_employer',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=16),
        ),
        migrations.AddField(
            model_name='salary',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('paid', 'Paid')], default='draft', max_length=12),
        ),
        migrations.AddField(
            model_name='salary',
            name='taxable_benefits',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salary',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Uganda PAYE withheld for this payroll period.', max_digits=16),
        ),
        migrations.RunPython(recalculate_existing_payroll, migrations.RunPython.noop),
    ]
