# Generated by Django 6.0.5 on 2026-07-15 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def group_existing_salary_records(apps, schema_editor):
    PayrollRun = apps.get_model('payroll', 'PayrollRun')
    Salary = apps.get_model('payroll', 'Salary')
    for salary in Salary.objects.all().iterator():
        payroll_run, _ = PayrollRun.objects.get_or_create(
            month=salary.month,
            year=salary.year,
            defaults={'status': salary.status},
        )
        if salary.status == 'paid' or (
            salary.status == 'approved' and payroll_run.status == 'draft'
        ):
            payroll_run.status = salary.status
            payroll_run.save(update_fields=['status'])
        salary.payroll_run = payroll_run
        salary.save(update_fields=['payroll_run'])


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_salary_chargeable_income_salary_gross_salary_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('paid', 'Paid')], default='draft', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_runs_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_runs_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('month', 'year')},
            },
        ),
        migrations.AddField(
            model_name='salary',
            name='payroll_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salary_records', to='payroll.payrollrun'),
        ),
        migrations.RunPython(group_existing_salary_records, migrations.RunPython.noop),
    ]
