# Generated by Django 6.0.5 on 2026-07-19 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_maturity_features'),
        ('payroll', '0006_require_payroll_run'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payrollrun',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_runs', to='accounts.organization'),
        ),
        migrations.AlterUniqueTogether(
            name='payrollrun',
            unique_together={('month', 'year', 'organization')},
        ),
    ]
