# Generated by Django 6.0.5 on 2026-05-25 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_employee_termination'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExitProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exit_date', models.DateField()),
                ('reason', models.CharField(choices=[('resignation', 'Resignation'), ('termination', 'Termination'), ('retirement', 'Retirement'), ('contract_end', 'Contract End'), ('redundancy', 'Redundancy'), ('death', 'Death')], max_length=50)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='initiated', max_length=20)),
                ('last_working_day', models.DateField(blank=True, null=True)),
                ('notice_period_days', models.IntegerField(default=30)),
                ('final_settlement_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('exit_interview_completed', models.BooleanField(default=False)),
                ('exit_interview_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exit_process', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ExitChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('responsible_person', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('not_applicable', 'Not Applicable')], default='pending', max_length=20)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exit_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='exits.exitprocess')),
            ],
            options={
                'ordering': ['exit_process', 'created_at'],
            },
        ),
    ]
