# Generated by Django 6.0.5 on 2026-07-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookdelivery',
            name='attempt_count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
