# Generated by Django 6.0.5 on 2026-07-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_maturity_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='scopes',
            field=models.JSONField(blank=True, default=list, help_text='Capability scopes for this key'),
        ),
    ]
