# Generated by Django 6.0.5 on 2026-07-19 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_maturity_features'),
        ('integrations', '0003_security_hardening'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_keys', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='webhookendpoint',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_endpoints', to='accounts.organization'),
        ),
    ]
