# Generated by Django 6.0.5 on 2026-05-20 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=14)),
                ('relationship', models.CharField(max_length=30)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kin', to='employees.employee')),
            ],
        ),
    ]
