# Generated by Django 6.0.5 on 2026-07-19 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_maturity_features'),
        ('attendance', '0002_publicholiday_attendance_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicholiday',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_holidays', to='accounts.organization'),
        ),
    ]
