# Generated by Django 6.0.5 on 2026-07-19 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_opsalertevent'),
        ('attendance', '0003_publicholiday_organization'),
        ('employees', '0009_employee_device_badge_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('import', 'Import'), ('timesheet', 'Timesheet'), ('device', 'Biometric / device'), ('mobile', 'Mobile')], default='manual', max_length=20),
        ),
        migrations.CreateModel(
            name='AttendanceDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('device_code', models.SlugField(max_length=64, unique=True)),
                ('device_type', models.CharField(choices=[('fingerprint', 'Fingerprint'), ('face', 'Face recognition'), ('rfid', 'RFID / badge'), ('mobile', 'Mobile app'), ('other', 'Other')], default='fingerprint', max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('token_prefix', models.CharField(editable=False, max_length=12, unique=True)),
                ('token_hash', models.CharField(editable=False, max_length=64)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_devices', to='accounts.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DevicePunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('punched_at', models.DateTimeField(db_index=True)),
                ('punch_type', models.CharField(choices=[('in', 'Clock in'), ('out', 'Clock out'), ('auto', 'Auto')], default='auto', max_length=8)),
                ('source', models.CharField(default='device', max_length=20)),
                ('client_punch_id', models.CharField(blank=True, db_index=True, help_text='Idempotency key from mobile offline queue.', max_length=64)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('applied', models.BooleanField(default=False)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_punches', to='attendance.attendance')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='punches', to='attendance.attendancedevice')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_punches', to='employees.employee')),
            ],
            options={
                'ordering': ['-punched_at'],
                'indexes': [models.Index(fields=['client_punch_id'], name='attendance__client__d0f384_idx')],
            },
        ),
    ]
