# Generated by Django 6.0.5 on 2026-07-19 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_maturity_features'),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certifications', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='skill',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_courses', to='accounts.organization'),
        ),
    ]
